---
- name: IOS Config Demo
  hosts: ios_conf_l3
  tasks:
    - name: Replaces device configuration of listed interfaces with provided configuration
      cisco.iosxr.iosxr_l3_interfaces:
        config:
          - name: GigabitEthernet0/0/0/3
            ipv6:
              - address: fd5d:12c9:2201:1::1/64
          - name: GigabitEthernet0/0/0/2
            ipv4:
              - address: 192.168.0.2/24
        state: replaced
