---
- name: IOS Config Demo
  hosts: ios_conf_l3
  tasks:
    - name: CONF INT 01
      cisco.iosxr.iosxr_l3_interfaces:
        config:
          - name: GigabitEthernet0/0/0/0
            ipv4:
              - address: 192.168.0.2/24
        state: merged
