---
- name: IOS Config Demo
  hosts: ios_conf_l3
  tasks:
    - name: configure interface settings
      cisco.iosxr.iosxr_config:
        lines:
        - description test interface
        - ip address 172.31.1.1 255.255.255.0
        parents: interface GigabitEthernet0/0/0/0